---
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      pyver: ${{ steps.pyenv.outputs.py_version }}
      greetings: ${{ steps.hello-world.outputs.stout }}
      script_ok: ${{ steps.script_passed.outputs.script_passed }}
      script_check: ${{ steps.pyenv.outcome }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Python virtual env
        id: pyenv
        run: |
          python3 -m venv ve1
          cd scripts
          echo "py_version=$(../ve1/bin/python web.py)" >> $GITHUB_OUTPUT

      - name: Check script passed
        id: script_passed
        run:
          echo "script_passed=${{ steps.pyenv.outcome }}" >> $GITHUB_OUTPUT

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: hello-world
        run: echo "stout=Hello, world!" >> $GITHUB_OUTPUT

  review:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get Python version
        if: ${{ needs.build.outputs.pyver }} != ""
        run:
          echo "${{ needs.build.outputs.pyver }}"
          echo ${{ needs.build.outputs.greetings }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Did Python script run
        run:
          echo ${{ needs.build.outputs.script_ok }}

      - name: Did Python script run p2
        run:
          echo ${{ needs.build.outputs.script_check }}

