---
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      greetings: ${{ steps.hello-world.outputs }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Python virtual env
        run: |
          python3 -m venv ve1
          cd scripts
          ../ve1/bin/python web.py

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: hello-world
        run: echo Hello, world! >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  review:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get Python version
        runs:
          echo ${{ needs.build.outputs.greetings }}
